name = "GameOne"
uuid = "b831c3d0-16f1-4eaa-ad23-1d0424ad4597"
authors = ["Dustin Irwin"]  # GameZero.jl authored by Avik Sengupta & Ahan Sengupta
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleDirectMediaLayer = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"

[compat]
Colors = "0.1"
SimpleDirectMediaLayer = "0.2"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
